### ISSUE TITLE
Mention that text is sent to remote server

### ISSUE THREAD

**Issue by justinormont** [thesofakillers/openai-gpt-2-browser-extension#2]
The Chrome/Firefox extension should directly mention that the text is sent to the huggingface server for analysis. When I read the description I assume the processing is run locally.

Current extension description:

> ...
> Luckily, OpenAI also released a detector which is designed to detect whether a given portion of text has been generated by GPT-2 or not.
> 
> This extension wraps the detector into a simple browser extension. Simply select a portion of text (at least 50 words) and the extension will let you know of the GPT-2 log probability that the text is indeed real.

https://github.com/thesofakillers/GPTrue-or-False/blob/45ea562f612eb30770d01898b3fa99e889a5f8ca/src/content/content.js#L43-L44

I wonder if someone tried running a RoBERTa model in a browser? I expect it would be excessively slow in either ONNX.js or TensorFlow.js. Perhaps interesting to see how slow.

Training the OpenAI GPT-2 detector: 
https://github.com/openai/gpt-2-output-dataset/tree/master/detector)

**Comment by thesofakillers** [comment]
Fixed in 7f6d815. See [DESCRIPTION.md](https://github.com/thesofakillers/GPTrue-or-False/blob/master/DESCRIPTION.md)

**Comment by justinormont** [comment]
Thanks for the fast fix.
